### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by piwel**
Creating a first version of the French translation for this plugin.

However, it would be better to also fix:
- the typography of the ":", in French, we use to add a non breakable space before each "_:"
- the format of the dates (we use the 24-hour format on the backend, and always use DD MMM instead of MMMM DD on the frontend part of the code)

Thanks for your work, this plugin is very useful!

### CODE REVIEW

**Comment by support-xylusthemes** [comment]
Hello @piwel ,

Thanks a lot for your contribution and sorry for didn't merge your PR yet. 

Many texts are changed since you made PR. would you like to update your translation?

Many Thanks

**Comment by piwel** [comment]
Hi @support-xylusthemes , here is the updated French translation!

**Comment by support-xylusthemes** [comment]
Hello @piwel , 

Hope you are doing well.

Thanks a lot for update translation. As there are many more files are also included in this PR. So, it will create issue if we merge this PR. Can you please help to create another PR which only include translation files. Or if its fine with you then we can directly pick translation file from your repository and will commit in our repo and will give you credit in readme file.

Thanks again

**Comment by piwel** [comment]
Yeahhhh… I'm not sure where these changes come from, it looks like Github reformatted a bit of code? Weird thing…

I only changed 7 files by myself (fixing some typos), you can just cherry-pick this commit if you can: https://github.com/piwel/import-facebook-events/commit/451da6f56fdee32876e306215c7081a90ef387dc

**Comment by support-xylusthemes** [comment]
Maybe Yes, some github issues. I will cherry-pick commit provided by you tomorrow. 

Thanks

**Comment by support-xylusthemes** [comment]
Hello @piwel ,

We have cherry picked your contribution and included in our plugin in version v1.6.12, you can changelog here(https://wordpress.org/plugins/import-facebook-events/#developers)

Thanks again for your great contribution.

**Pull request closed without merging**
